### ISSUE TITLE
Crosshair sync doesn't work as expected

### ISSUE THREAD

**Issue by shreya2701** [jamesbrobb/ngx-lightweight-charts#5] opened 2024-07-08 05:43 UTC
I have encountered an issue with the sync Crosshair feature in this library. When attempting to synchronize the crosshair across multiple charts, it does not function as expected. I have one array of charts which contains charts dynamically and the number of charts on the screen can be changed.

**Issue 1:**
When there are two charts in your `tvChartCollector` wrapper, if I move crosshair on the above chart it won't sync with chart 2 (as shown in below image) and if I move crosshair in chart 2 it will works as expected.

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/86658485/bd0aedbc-1f6e-48e5-a30f-0b2368bfab71)

**Issue 2:**
Let's say I have 3 charts in the `tvChartCollector` wrapper, then If I move crosshair in chart one then I doesn't work in 2 another charts (as shown in 1st image) and if I move crosshair in another 2 charts then it will work in respective chart and chart one only (as shown in below 2nd and 3rd images).

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/86658485/fb548952-1449-407f-b4b2-4e1323541c01)

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/86658485/71184cca-d112-4ead-879f-21100e30b060)

![image](https://github.com/jamesbrobb/ngx-lightweight-charts/assets/86658485/2cafdb6d-8c58-48fb-b9a2-d527cf08c9a7)

**Code:**
```
<div tvChartCollector tvChartSync>
      <tv-candlestick-chart id="one" [data]="[]" (initialised)="onMainChartInit($event)" [options]="chartOptions"
        (visibleLogicalRangeChanged)="loadAdditionalDataIfNeeded($event)"></tv-candlestick-chart>
      @for (chart of getIndicatorCharts();let i = $index; track i) {
      <div tvChart="Line" [id]="i.toString()" [data]="[]" (initialised)="onIndicatorChartInit($event, chart.id)"
        [options]="chartOptions" (visibleLogicalRangeChanged)="loadAdditionalDataIfNeeded($event)"></div>
      }
</div>
```

**Comment by jamesbrobb** [comment] 2024-07-08 15:42
Thanks for raising this issue.

Please can you create a minimal reproduction that demonstrates the issue you're having?

I've attempted this myself, but unfortunately am unable to reproduce the behaviour you're seeing - please see the following [branch](https://github.com/jamesbrobb/ngx-lightweight-charts/blob/5-crosshair-sync-doesnt-work-as-expected/projects/examples/src/app/components/issues/issue-%235/issue-5/issue-5.component.ts)

---

However, i did find two other issues whilst looking at this:

1. When a new chart was added its visible logical range wasn't being updated to match the current visible logical range of the existing charts.
2. When setting `timeScale.lockVisibleTimeRangeOnResize` to `true` (which is the default), resizing a chart does not (understandably) output a new logical range. So if the width of the existing chart is updated and the chart is not zoomed or scrolled, when a new chart is added it's current scale/position is incorrect.

These are both now fixed and a new version has been published. 

---

It's probably worth installing the latest version to see if it makes a difference, but looking at your screenshots, as all the horizontal scale values line up, i don't think this is the cause of your issue.

**Comment by shreya2701** [comment] 2024-07-09 11:17
I found the solution to my problem.
I am not using the default series which we get at the `initialization` of the `chart`.
 
**Example:**
Let's say I have 4 series in one chart. then, one should be the default, provided after `initialization` and three will be added using `addAdditionalSeries()`. But, I was adding four new series instead of using one default and adding three new series.
 
The issue is resolved, but you may add `functionality` where you use any chart series for `crosshair syncing` instead of the default one.

**Comment by jamesbrobb** [comment] 2024-07-09 13:27
Ah, that's interesting, thanks for the explanation.

So the default was simply not used as no data was supplied, even though it had been initialised?

**Closed as completed** 2024-07-10 13:34 UTC
Labels: bug
